services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
    volumes:
      - ./postgress/data:/var/lib/postgresql/data
    restart: always
  
  
  app:
    build:
      context: .
    image: app
    container_name: django-app
    hostname: automail.fums.ac.ir
    volumes:
      - static:/app/static
      - ./logs/sms:/var/log/sms
      - ./logs/mail/mail.log:/var/log/mail.log
      - ./logs/mail/procmail.log:/var/log/procmail.log
      - ./usersconf/passwd:/etc/passwd:rw
      
    command: >
      sh -c   "postfix start &&
              python manage.py migrate &&
             python manage.py collectstatic --no-input  &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
             
    
    depends_on:
      - database
    ports:
      - "25:25"       # SMTP (for receiving emails)
      - "587:587"     # Submission (for client email submissions)
      - "143:143"
    environment:
      - DEBUG=False
      # - ALLOWED_HOSTS=*
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
      - ./nginxconf:/etc/nginx/conf.d
      # - media:/var/www/media 
   
    depends_on:
      - app
    restart: always
volumes:
  static:
  # user_data:
  #  external: true
  
  # postgres:
  # media: