services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgress/data:/var/lib/postgresql/data
    restart: always
  
  
  app:
    build:
      context: .
    image: app
    container_name: django-app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input  &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      # - media:/usr/src/app/media
    depends_on:
      - database
    environment:
      - DEBUG=False
      # - ALLOWED_HOSTS=*
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432


  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/var/www/static
      # - media:/var/www/media 
    
  
volumes:
  static:
  # postgres:
  # media: