# Generated by Django 5.1.2 on 2024-10-16 16:57

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrsmgmnt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiGateUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
            ],
        ),
        migrations.AlterField(
            model_name='linfortiusers',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[utils.validators.validate_national_code], verbose_name='کد ملی '),
        ),
        migrations.AlterField(
            model_name='linfortiusers',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name=' شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='linfortiusers',
            name='username',
            field=models.CharField(help_text='لطفاً یک نام کاربری انتخاب کنید که فقط شامل حروف، اعداد و علامات مجاز باشد.', max_length=150, unique=True, validators=[utils.validators.validate_linux_username], verbose_name='نام کاربری'),
        ),
        migrations.AddField(
            model_name='linfortiusers',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usrsmgmnt.fortigateusergroup', verbose_name='گروه کاربری FortiGate'),
        ),
    ]
