# Generated by Django 5.1.2 on 2024-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrsmgmnt', '0002_fortigateusergroup_alter_linfortiusers_national_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortigateusergroup',
            old_name='name',
            new_name='fortigate_name',
        ),
        migrations.AddField(
            model_name='fortigateusergroup',
            name='fortigate_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='شناسه FortiGate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linfortiusers',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name=' شماره موبایل'),
        ),
    ]
