# Generated by Django 5.1.2 on 2024-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrsmgmnt', '0003_rename_name_fortigateusergroup_fortigate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortigateusergroup',
            name='fortigate_id',
            field=models.IntegerField(unique=True, verbose_name='شناسه FortiGate'),
        ),
    ]
